/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menutienda;

import javax.swing.JOptionPane;

/**
 *
 * @author cruz-
 */
public class ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form ventana1
     */
    public ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    double pHamburg = 20.00;
    double pDogo = 15.00;
    double pSoda = 25.00;
    double pQCQ = 35.00;
    double pQSQ = 30.00;
    double pBurrito = 125.00;
    double pParrillada = 700;
    Calculos purchase = new Calculos();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        RBtn1 = new javax.swing.JRadioButton();
        RBtn3 = new javax.swing.JRadioButton();
        RBtn2 = new javax.swing.JRadioButton();
        RBtn4 = new javax.swing.JRadioButton();
        BtnCleanFields = new javax.swing.JButton();
        CheckBoxhamburg = new javax.swing.JCheckBox();
        CheckBoxDogo = new javax.swing.JCheckBox();
        txtPrecioHamburg = new javax.swing.JTextField();
        txtPrecioDogo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CheckBoxQCQ = new javax.swing.JCheckBox();
        CheckBoxSoda = new javax.swing.JCheckBox();
        CheckBoxQSQ = new javax.swing.JCheckBox();
        CheckBoxBurrito = new javax.swing.JCheckBox();
        CheckBoxGrill = new javax.swing.JCheckBox();
        txtSodaPrecio = new javax.swing.JTextField();
        txtQCQprecio = new javax.swing.JTextField();
        txtQSQprecio = new javax.swing.JTextField();
        txtBurrito = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtGrill = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBill = new javax.swing.JTextField();
        getBill = new javax.swing.JButton();
        BtnLeave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Phosphate", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Promociones");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 120, 30));

        buttonGroup1.add(RBtn1);
        RBtn1.setFont(new java.awt.Font("Marker Felt", 1, 14)); // NOI18N
        RBtn1.setText("Sin Descuento");
        RBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(RBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        buttonGroup1.add(RBtn3);
        RBtn3.setFont(new java.awt.Font("Marker Felt", 1, 14)); // NOI18N
        RBtn3.setText("Targeta de Promoción");
        RBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(RBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        buttonGroup1.add(RBtn2);
        RBtn2.setFont(new java.awt.Font("Marker Felt", 1, 14)); // NOI18N
        RBtn2.setText("Cliente Frecuente 20% de descuento");
        getContentPane().add(RBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        buttonGroup1.add(RBtn4);
        RBtn4.setFont(new java.awt.Font("Marker Felt", 1, 14)); // NOI18N
        RBtn4.setText("Descuento de Internet 10%");
        RBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(RBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        BtnCleanFields.setBackground(new java.awt.Color(255, 51, 51));
        BtnCleanFields.setFont(new java.awt.Font("Marker Felt", 1, 14)); // NOI18N
        BtnCleanFields.setText("Limpiar Campos");
        BtnCleanFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCleanFieldsActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCleanFields, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        CheckBoxhamburg.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        CheckBoxhamburg.setForeground(new java.awt.Color(204, 51, 0));
        CheckBoxhamburg.setText("Hamburguesa Long Rodeo");
        CheckBoxhamburg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxhamburgActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBoxhamburg, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        CheckBoxDogo.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        CheckBoxDogo.setForeground(new java.awt.Color(204, 51, 0));
        CheckBoxDogo.setText("Super HotDog");
        getContentPane().add(CheckBoxDogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));
        getContentPane().add(txtPrecioHamburg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 60, -1));

        txtPrecioDogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioDogoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPrecioDogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 60, -1));

        jLabel3.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        jLabel3.setText("$20.00");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        jLabel4.setText("$15.00");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        CheckBoxQCQ.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        CheckBoxQCQ.setForeground(new java.awt.Color(255, 51, 51));
        CheckBoxQCQ.setText("quesadilla con queso");
        getContentPane().add(CheckBoxQCQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, -1, -1));

        CheckBoxSoda.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        CheckBoxSoda.setForeground(new java.awt.Color(255, 51, 51));
        CheckBoxSoda.setText("Refrescos");
        getContentPane().add(CheckBoxSoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        CheckBoxQSQ.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        CheckBoxQSQ.setForeground(new java.awt.Color(255, 51, 51));
        CheckBoxQSQ.setText("qusadilla sin queso");
        getContentPane().add(CheckBoxQSQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        CheckBoxBurrito.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        CheckBoxBurrito.setForeground(new java.awt.Color(255, 0, 0));
        CheckBoxBurrito.setText("Burrito de Arrachera");
        getContentPane().add(CheckBoxBurrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        CheckBoxGrill.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        CheckBoxGrill.setForeground(new java.awt.Color(255, 51, 51));
        CheckBoxGrill.setText("Parrillada");
        getContentPane().add(CheckBoxGrill, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        txtSodaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSodaPrecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtSodaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, 80, -1));

        txtQCQprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQCQprecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtQCQprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 80, -1));

        txtQSQprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQSQprecioActionPerformed(evt);
            }
        });
        getContentPane().add(txtQSQprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 80, -1));

        txtBurrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBurritoActionPerformed(evt);
            }
        });
        getContentPane().add(txtBurrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 80, -1));

        jLabel5.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        jLabel5.setText("$ 25.00");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        jLabel6.setText("$ 35.00");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        jLabel7.setText("$ 30.00");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        jLabel8.setText("$ 125.00");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        txtGrill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrillActionPerformed(evt);
            }
        });
        getContentPane().add(txtGrill, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 80, -1));

        jLabel9.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        jLabel9.setText("$ 700.00");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, 20));

        jLabel10.setFont(new java.awt.Font("Marker Felt", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Total a Pagar :$");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, 20));

        txtBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillActionPerformed(evt);
            }
        });
        getContentPane().add(txtBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 90, 20));

        getBill.setFont(new java.awt.Font("Marker Felt", 1, 14)); // NOI18N
        getBill.setText("Obtener el Total a pagar");
        getBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBillActionPerformed(evt);
            }
        });
        getContentPane().add(getBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        BtnLeave.setFont(new java.awt.Font("Marker Felt", 1, 14)); // NOI18N
        BtnLeave.setText("Salir de la App");
        BtnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLeaveActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLeave, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/foto1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBtn3ActionPerformed

    private void RBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBtn4ActionPerformed

    private void txtPrecioDogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioDogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioDogoActionPerformed

    private void txtBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBillActionPerformed

    private void txtSodaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSodaPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSodaPrecioActionPerformed

    private void txtQSQprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQSQprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQSQprecioActionPerformed

    private void txtBurritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBurritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBurritoActionPerformed

    private void txtGrillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrillActionPerformed

    private void getBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBillActionPerformed
        // TODO add your handling code here:
        if(RBtn1.isSelected()){
            double total=0;
            if(CheckBoxhamburg.isSelected()){
                double x = Double.parseDouble(txtPrecioHamburg.getText());
                total = pHamburg*x;
            }
            if(CheckBoxDogo.isSelected()){
                double y = Double.parseDouble(txtPrecioDogo.getText());
                total = total + (pDogo*y);
            }
            if(CheckBoxSoda.isSelected()){
                double x2 = Double.parseDouble(txtSodaPrecio.getText());
                total = total + (pSoda*x2);
            }
            if(CheckBoxQCQ.isSelected()){
                double x3 = Double.parseDouble(txtQCQprecio.getText());
                total = total + (pQCQ*x3);
            }
            if(CheckBoxQSQ.isSelected()){
                double x4 = Double.parseDouble(txtQSQprecio.getText());
                total = total + (pQSQ*x4);
            }
            if(CheckBoxBurrito.isSelected()){
                double x5 = Double.parseDouble(txtBurrito.getText());
                total = total + (pBurrito*x5);
            }
            if(CheckBoxGrill.isSelected()){
                double x7 = Double.parseDouble(txtGrill.getText());
                total = total + (pParrillada*x7);
            }
            txtBill.setText(""+total);
        }
        if(RBtn2.isSelected()){
            double total=0;
            if(CheckBoxhamburg.isSelected()){
                double x = Double.parseDouble(txtPrecioHamburg.getText());
                total = pHamburg*x;
            }
            if(CheckBoxDogo.isSelected()){
                double y = Double.parseDouble(txtPrecioDogo.getText());
                total = total + (pDogo*y);
            }
            if(CheckBoxSoda.isSelected()){
                double x2 = Double.parseDouble(txtSodaPrecio.getText());
                total = total + (pSoda*x2);
            }
            if(CheckBoxQCQ.isSelected()){
                double x3 = Double.parseDouble(txtQCQprecio.getText());
                total = total + (pQCQ*x3);
            }
            if(CheckBoxQSQ.isSelected()){
                double x4 = Double.parseDouble(txtQSQprecio.getText());
                total = total + (pQSQ*x4);
            }
            if(CheckBoxBurrito.isSelected()){
                double x5 = Double.parseDouble(txtBurrito.getText());
                total = total + (pBurrito*x5);
            }
            if(CheckBoxGrill.isSelected()){
                double x7 = Double.parseDouble(txtGrill.getText());
                total = total + (pParrillada*x7);
            }
        
            txtBill.setText(""+purchase.conDescuento(total));
        }
        if(RBtn3.isSelected()){
            double total=0;
            if(CheckBoxhamburg.isSelected()){
                double x = Double.parseDouble(txtPrecioHamburg.getText());
                total = pHamburg*x;
            }
            if(CheckBoxDogo.isSelected()){
                double y = Double.parseDouble(txtPrecioDogo.getText());
                total = total + (pDogo*y);
            }
            if(CheckBoxSoda.isSelected()){
                double x2 = Double.parseDouble(txtSodaPrecio.getText());
                total = total + (pSoda*x2);
            }
            if(CheckBoxQCQ.isSelected()){
                double x3 = Double.parseDouble(txtQCQprecio.getText());
                total = total + (pQCQ*x3);
            }
            if(CheckBoxQSQ.isSelected()){
                double x4 = Double.parseDouble(txtQSQprecio.getText());
                total = total + (pQSQ*x4);
            }
            if(CheckBoxBurrito.isSelected()){
                double x5 = Double.parseDouble(txtBurrito.getText());
                total = total + (pBurrito*x5);
            }
            if(CheckBoxGrill.isSelected()){
                double x7 = Double.parseDouble(txtGrill.getText());
                total = total + (pParrillada*x7);
            }
            JOptionPane.showMessageDialog(null,"Por tu targeta de promocion te regalamos 2 hamburguesas gratis Gracias");
            txtBill.setText(""+total);
        }
        if(RBtn4.isSelected()){
            double total=0;
            if(CheckBoxhamburg.isSelected()){
                double x = Double.parseDouble(txtPrecioHamburg.getText());
                total = pHamburg*x;
            }
            if(CheckBoxDogo.isSelected()){
                double y = Double.parseDouble(txtPrecioDogo.getText());
                total = total + (pDogo*y);
            }
            if(CheckBoxSoda.isSelected()){
                double x2 = Double.parseDouble(txtSodaPrecio.getText());
                total = total + (pSoda*x2);
            }
            if(CheckBoxQCQ.isSelected()){
                double x3 = Double.parseDouble(txtQCQprecio.getText());
                total = total + (pQCQ*x3);
            }
            if(CheckBoxQSQ.isSelected()){
                double x4 = Double.parseDouble(txtQSQprecio.getText());
                total = total + (pQSQ*x4);
            }
            if(CheckBoxBurrito.isSelected()){
                double x5 = Double.parseDouble(txtBurrito.getText());
                total = total + (pBurrito*x5);
            }
            if(CheckBoxGrill.isSelected()){
                double x7 = Double.parseDouble(txtGrill.getText());
                total = total + (pParrillada*x7);
            }
        
            txtBill.setText(""+purchase.conDescuentoInternet(total));
        }
        
    }//GEN-LAST:event_getBillActionPerformed

    private void txtQCQprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQCQprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQCQprecioActionPerformed

    private void BtnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLeaveActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BtnLeaveActionPerformed

    private void BtnCleanFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCleanFieldsActionPerformed
        // TODO add your handling code here:
        if(CheckBoxBurrito.isSelected())
            CheckBoxBurrito.setSelected(false);
        if(CheckBoxDogo.isSelected())
            CheckBoxDogo.setSelected(false);
        if(CheckBoxGrill.isSelected())
            CheckBoxGrill.setSelected(false);
        if(CheckBoxQCQ.isSelected())
            CheckBoxQCQ.setSelected(false);
        if(CheckBoxQSQ.isSelected())
            CheckBoxQSQ.setSelected(false);
        if(CheckBoxSoda.isSelected())
            CheckBoxSoda.setSelected(false);
        if(CheckBoxDogo.isSelected())
            CheckBoxDogo.setSelected(false);
        if(CheckBoxhamburg.isSelected())
            CheckBoxhamburg.setSelected(false);
        if(RBtn1.isSelected())
            RBtn1.setSelected(false);
        if(RBtn2.isSelected())
            RBtn2.setSelected(false);
        if(RBtn3.isSelected())
            RBtn3.setSelected(false);
        if(RBtn4.isSelected())
            RBtn4.setSelected(false);
        txtBill.setText("");
        txtSodaPrecio.setText("");
        txtBurrito.setText("");
        txtGrill.setText("");
        txtPrecioDogo.setText("");
        txtPrecioHamburg.setText("");
        txtQCQprecio.setText("");
        txtQSQprecio.setText("");
    }//GEN-LAST:event_BtnCleanFieldsActionPerformed

    private void CheckBoxhamburgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxhamburgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxhamburgActionPerformed

    private void RBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCleanFields;
    private javax.swing.JButton BtnLeave;
    public javax.swing.JCheckBox CheckBoxBurrito;
    public javax.swing.JCheckBox CheckBoxDogo;
    public javax.swing.JCheckBox CheckBoxGrill;
    public javax.swing.JCheckBox CheckBoxQCQ;
    public javax.swing.JCheckBox CheckBoxQSQ;
    public javax.swing.JCheckBox CheckBoxSoda;
    public javax.swing.JCheckBox CheckBoxhamburg;
    private javax.swing.JRadioButton RBtn1;
    private javax.swing.JRadioButton RBtn2;
    private javax.swing.JRadioButton RBtn3;
    private javax.swing.JRadioButton RBtn4;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton getBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField txtBill;
    private javax.swing.JTextField txtBurrito;
    private javax.swing.JTextField txtGrill;
    public javax.swing.JTextField txtPrecioDogo;
    public javax.swing.JTextField txtPrecioHamburg;
    public javax.swing.JTextField txtQCQprecio;
    public javax.swing.JTextField txtQSQprecio;
    public javax.swing.JTextField txtSodaPrecio;
    // End of variables declaration//GEN-END:variables
}
